import { PageHeading } from "@/components/ui/page-heading";
import { Badge } from "@/components/ui/badge";
import { PasswordForm } from "@/components/employee/password-form";
import { getCurrentEmployee } from "@/lib/data/employees";

export default async function ProfilePage() {
  const person = await getCurrentEmployee();
  const initials = person.name.split(" ").map((value) => value[0]).join("");
  return <><PageHeading eyebrow="Account" title="Your profile" description="Your account and employment details." /><section className="panel overflow-hidden"><div className="h-28 bg-[linear-gradient(120deg,var(--brand),#3e806b)]" /><div className="px-5 pb-6 sm:px-8"><div className="-mt-10 flex flex-col items-start gap-4 sm:flex-row sm:items-end"><span className="grid size-20 place-items-center rounded-3xl border-4 border-white bg-[var(--accent-soft)] text-xl font-black text-[var(--warning)]">{initials}</span><div className="pb-1"><h2 className="font-display text-2xl font-bold">{person.name}</h2><p className="text-sm text-[var(--muted)]">{person.position}</p></div><Badge className="sm:ml-auto sm:mb-2" tone="brand">{person.classification}</Badge></div><dl className="mt-8 grid gap-5 border-t border-[var(--line)] pt-6 sm:grid-cols-2"><div><dt className="text-xs font-bold uppercase tracking-wide text-[var(--muted)]">Username</dt><dd className="mt-1 text-sm font-semibold">@{person.username ?? "Not set"}</dd></div><div><dt className="text-xs font-bold uppercase tracking-wide text-[var(--muted)]">Phone</dt><dd className="mt-1 text-sm font-semibold">{person.phone || "Not provided"}</dd></div><div><dt className="text-xs font-bold uppercase tracking-wide text-[var(--muted)]">Employee ID</dt><dd className="mt-1 text-sm font-semibold">{person.id.slice(0, 8).toUpperCase()}</dd></div><div><dt className="text-xs font-bold uppercase tracking-wide text-[var(--muted)]">Account status</dt><dd className="mt-1 text-sm font-semibold text-[var(--success)]">{person.active ? "Active" : "Inactive"}</dd></div></dl></div></section><PasswordForm /></>;
}
