create type account_role as enum ('manager','employee');
create type employee_classification as enum ('FreeSched','Working Student');
create type shift_period as enum ('Morning','Afternoon','Evening');
create type request_status as enum ('pending','approved','declined','cancelled');
create type schedule_status as enum ('draft','published','revised');

create table profiles (id text primary key,full_name text not null,email text not null unique,phone text,role account_role not null default 'employee',classification employee_classification not null default 'FreeSched',preferred_period shift_period,position text not null default 'Service Crew',active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table class_meetings (id uuid primary key default gen_random_uuid(),employee_id text not null references profiles on delete cascade,weekday smallint not null check(weekday between 1 and 7),subject text not null,starts_at time not null,ends_at time not null check(ends_at>starts_at),created_at timestamptz not null default now());
create table rest_day_requests (id uuid primary key default gen_random_uuid(),employee_id text not null references profiles on delete cascade,requested_date date not null,reason text not null check(char_length(reason) between 3 and 500),status request_status not null default 'pending',submitted_at timestamptz not null default now(),reviewed_at timestamptz,reviewed_by text references profiles,manager_note text,unique(employee_id,requested_date));
create table schedules (id uuid primary key default gen_random_uuid(),week_start date not null unique check(extract(isodow from week_start)=1),status schedule_status not null default 'draft',published_at timestamptz,published_by text references profiles,revision integer not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table shifts (id uuid primary key default gen_random_uuid(),schedule_id uuid not null references schedules on delete cascade,employee_id text not null references profiles on delete cascade,starts_at timestamptz not null,ends_at timestamptz not null check(ends_at>starts_at),label text not null,break_minutes integer not null default 60 check(break_minutes>=0),created_at timestamptz not null default now());
create table shift_templates (id uuid primary key default gen_random_uuid(),name text not null unique,starts_at time not null,ends_at time not null,break_minutes integer not null default 60 check(break_minutes>=0));
create table scheduling_settings (id boolean primary key default true check(id),week_starts smallint not null default 1 check(week_starts=1),finalization_weekday smallint not null default 5 check(finalization_weekday between 1 and 7),updated_at timestamptz not null default now());
create table notifications (id uuid primary key default gen_random_uuid(),recipient_id text not null references profiles on delete cascade,title text not null,message text not null,read_at timestamptz,created_at timestamptz not null default now());
create index requests_queue_idx on rest_day_requests(requested_date,submitted_at) where status='pending';create index shifts_employee_time_idx on shifts(employee_id,starts_at,ends_at);create index notifications_recipient_idx on notifications(recipient_id,created_at desc);

-- Used by the Neon Data API. Server-side application queries also enforce roles.
create or replace function is_manager() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from profiles where id=auth.user_id() and role='manager' and active)$$;
alter table profiles enable row level security;alter table class_meetings enable row level security;alter table rest_day_requests enable row level security;alter table schedules enable row level security;alter table shifts enable row level security;alter table shift_templates enable row level security;alter table scheduling_settings enable row level security;alter table notifications enable row level security;
create policy profiles_read on profiles for select to authenticated using(id=auth.user_id() or is_manager());create policy profiles_manager_write on profiles for all to authenticated using(is_manager()) with check(is_manager());create policy classes_read on class_meetings for select to authenticated using(employee_id=auth.user_id() or is_manager());create policy classes_self_write on class_meetings for all to authenticated using(employee_id=auth.user_id()) with check(employee_id=auth.user_id());create policy classes_manager_write on class_meetings for all to authenticated using(is_manager()) with check(is_manager());
create policy requests_read on rest_day_requests for select to authenticated using(employee_id=auth.user_id() or is_manager());create policy requests_submit on rest_day_requests for insert to authenticated with check(employee_id=auth.user_id() and status='pending');create policy requests_cancel on rest_day_requests for update to authenticated using(employee_id=auth.user_id() and status='pending') with check(employee_id=auth.user_id() and status='cancelled');create policy requests_review on rest_day_requests for update to authenticated using(is_manager()) with check(is_manager());
create policy schedules_read on schedules for select to authenticated using(status in('published','revised') or is_manager());create policy schedules_manage on schedules for all to authenticated using(is_manager()) with check(is_manager());create policy shifts_read on shifts for select to authenticated using((employee_id=auth.user_id() and exists(select 1 from schedules where schedules.id=shifts.schedule_id and status in('published','revised'))) or is_manager());create policy shifts_manage on shifts for all to authenticated using(is_manager()) with check(is_manager());
create policy templates_read on shift_templates for select to authenticated using(true);create policy templates_manage on shift_templates for all to authenticated using(is_manager()) with check(is_manager());create policy settings_read on scheduling_settings for select to authenticated using(true);create policy settings_manage on scheduling_settings for all to authenticated using(is_manager()) with check(is_manager());create policy notifications_read on notifications for select to authenticated using(recipient_id=auth.user_id());create policy notifications_update on notifications for update to authenticated using(recipient_id=auth.user_id()) with check(recipient_id=auth.user_id());create policy notifications_create on notifications for insert to authenticated with check(is_manager());
grant usage on schema public to authenticated;grant select,insert,update,delete on all tables in schema public to authenticated;grant usage,select on all sequences in schema public to authenticated;
