"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { Employee } from "@/types";
import { resetTeamAccountPassword, setTeamAccountActive, updateTeamAccount } from "@/app/actions/employees";

export function AccountActions({ person }: { person: Employee }) {
  const router = useRouter(); const [mode,setMode]=useState<"edit"|"password"|null>(null); const [error,setError]=useState("");
  async function edit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const result=await updateTeamAccount(person.id,new FormData(event.currentTarget));if(!result.ok){setError(result.error??"Could not update account.");return}setMode(null);router.refresh()}
  async function reset(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const password=String(new FormData(event.currentTarget).get("password"));const result=await resetTeamAccountPassword(person.id,password);if(!result.ok){setError(result.error??"Could not reset password.");return}setMode(null)}
  async function toggle(){await setTeamAccountActive(person.id,!person.active);router.refresh()}
  return <><div className="flex flex-wrap gap-1"><button className="button button-ghost px-2 text-xs" onClick={()=>{setMode("edit");setError("")}}>Edit</button><button className="button button-ghost px-2 text-xs" onClick={()=>{setMode("password");setError("")}}>Password</button><button className={`button button-ghost px-2 text-xs ${person.active?"text-[var(--danger)]":"text-[var(--success)]"}`} onClick={toggle}>{person.active?"Deactivate":"Activate"}</button></div>{mode&&<div className="fixed inset-0 z-50 grid place-items-center bg-[#17251f]/45 p-4"><form onSubmit={mode==="edit"?edit:reset} className="panel w-full max-w-md p-6"><h2 className="font-display text-xl font-bold">{mode==="edit"?"Edit account":"Reset password"}</h2>{mode==="edit"?<div className="mt-4 space-y-3"><input className="field" name="name" defaultValue={person.name} placeholder="Full name" required/><input className="field" name="position" defaultValue={person.position} placeholder="Position" required/>{person.role==="employee"&&<select className="field" name="classification" defaultValue={person.classification}><option>FreeSched</option><option>Working Student</option></select>}</div>:<div className="mt-4"><label className="label">New temporary password</label><input className="field" name="password" type="password" minLength={8} required/></div>}{error&&<p className="mt-3 rounded-xl bg-[var(--danger-soft)] p-3 text-sm text-[var(--danger)]">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button type="button" className="button button-ghost" onClick={()=>setMode(null)}>Cancel</button><button className="button button-primary">Save</button></div></form></div>}</>;
}
