"use client";
import { useState } from "react";
import { saveSchedulingSettings } from "@/app/actions/settings";
import type { SchedulingSettings, ShiftTemplate } from "@/lib/data/settings";
import { Plus } from "@/components/ui/icons";

export function SettingsForm({ initial }: { initial: SchedulingSettings }) {
  const [templates, setTemplates] = useState(initial.templates);
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");
  const update = (index: number, patch: Partial<ShiftTemplate>) => setTemplates(templates.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item));
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); form.set("templates", JSON.stringify(templates)); const result = await saveSchedulingSettings(form); if (!result.ok) { setError(result.error ?? "Settings could not be saved."); setNotice(""); return; } setError(""); setNotice("Scheduling settings saved."); }
  return <form onSubmit={submit} className="space-y-6">{notice && <div role="status" className="rounded-xl bg-[var(--success-soft)] px-4 py-3 text-sm font-semibold text-[var(--success)]">{notice}</div>}{error && <div role="alert" className="rounded-xl bg-[var(--danger-soft)] px-4 py-3 text-sm font-semibold text-[var(--danger)]">{error}</div>}<section className="panel p-5 sm:p-6"><h2 className="font-display text-xl font-bold">Schedule rules</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><label className="label">Minimum crew scheduled each day</label><input className="field" name="minimumDailyCrew" type="number" defaultValue={initial.minimumDailyCrew} min="1" max="50" required /></div><div><label className="label">Target finalization day</label><select className="field" name="finalizationWeekday" defaultValue={initial.finalizationWeekday}>{["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"].map((day,index)=><option key={day} value={index+1}>{day}</option>)}</select></div></div></section><section className="panel p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-xl font-bold">Shift templates</h2><p className="mt-1 text-sm text-[var(--muted)]">The generator spreads crew across these overlapping shifts.</p></div><button type="button" className="button button-secondary" onClick={()=>setTemplates([...templates,{id:crypto.randomUUID(),name:"New shift",start:"08:00",end:"17:00",breakMinutes:60}])}><Plus className="size-4"/>Add shift</button></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{templates.map((template,index)=><div key={template.id} className="rounded-2xl bg-[var(--surface)] p-4"><input aria-label="Template name" className="field" value={template.name} onChange={(event)=>update(index,{name:event.target.value})}/><div className="mt-3 grid grid-cols-2 gap-2"><input aria-label={`${template.name} start`} className="field" type="time" value={template.start} onChange={(event)=>update(index,{start:event.target.value})}/><input aria-label={`${template.name} end`} className="field" type="time" value={template.end} onChange={(event)=>update(index,{end:event.target.value})}/></div><label className="label mt-3">Break minutes</label><input className="field" type="number" min="0" value={template.breakMinutes} onChange={(event)=>update(index,{breakMinutes:Number(event.target.value)})}/><button type="button" disabled={templates.length===1} className="button button-ghost mt-2 text-[var(--danger)]" onClick={()=>setTemplates(templates.filter((_,itemIndex)=>itemIndex!==index))}>Remove</button></div>)}</div></section><button className="button button-primary">Save settings</button></form>;
}
