"use client";
import { useState } from "react";
const rows=[{day:"Monday",subject:"Accounting",start:"09:00",end:"12:00"},{day:"Wednesday",subject:"Business Law",start:"10:00",end:"13:00"},{day:"Friday",subject:"Economics",start:"08:00",end:"11:00"}];
export function AvailabilityForm(){
  const[period,setPeriod]=useState("Evening");const[saved,setSaved]=useState(false);
  return <form onSubmit={e=>{e.preventDefault();setSaved(true)}} className="space-y-6">
    {saved&&<div role="status" className="rounded-xl bg-[var(--success-soft)] px-4 py-3 text-sm font-semibold text-[var(--success)]">Availability saved.</div>}
    <section className="panel p-5 sm:p-6"><h2 className="font-display text-xl font-bold">Preferred shift period</h2><p className="mt-1 text-sm text-[var(--muted)]">A preference helps your manager plan; it does not guarantee an assignment.</p><div className="mt-5 grid gap-3 sm:grid-cols-3">{["Morning","Afternoon","Evening"].map(item=><label key={item} className={`cursor-pointer rounded-2xl border p-4 text-sm font-bold ${period===item?"border-[var(--brand)] bg-[var(--brand-soft)] text-[var(--brand)]":"border-[var(--line)] bg-white"}`}><input className="sr-only" type="radio" name="period" checked={period===item} onChange={()=>{setPeriod(item);setSaved(false)}}/>{item}<span className="mt-1 block text-xs font-normal text-[var(--muted)]">{item==="Morning"?"Opening – noon":item==="Afternoon"?"Noon – dinner":"Dinner – closing"}</span></label>)}</div></section>
    <section className="panel p-5 sm:p-6"><h2 className="font-display text-xl font-bold">Class schedule</h2><p className="mt-1 text-sm text-[var(--muted)]">Work shifts must not overlap these recorded classes.</p><div className="mt-5 space-y-3">{rows.map(row=><div key={row.day} className="grid gap-3 rounded-2xl bg-[var(--surface)] p-4 sm:grid-cols-4"><div><label className="label">Day</label><select className="field" defaultValue={row.day}><option>{row.day}</option></select></div><div><label className="label">Subject</label><input className="field" defaultValue={row.subject}/></div><div><label className="label">Starts</label><input className="field" type="time" defaultValue={row.start}/></div><div><label className="label">Ends</label><input className="field" type="time" defaultValue={row.end}/></div></div>)}</div><button className="button button-primary mt-5" type="submit">Save availability</button></section>
  </form>
}
