create type public.account_role as enum ('manager','employee');
create type public.employee_classification as enum ('FreeSched','Working Student');
create type public.shift_period as enum ('Morning','Afternoon','Evening');
create type public.request_status as enum ('pending','approved','declined','cancelled');
create type public.schedule_status as enum ('draft','published','revised');

create table public.profiles (id uuid primary key references auth.users on delete cascade, full_name text not null, email text not null, phone text, role account_role not null default 'employee', classification employee_classification not null default 'FreeSched', preferred_period shift_period, position text not null default 'Service Crew', active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.class_meetings (id uuid primary key default gen_random_uuid(), employee_id uuid not null references public.profiles on delete cascade, weekday smallint not null check(weekday between 1 and 7), subject text not null, starts_at time not null, ends_at time not null check(ends_at>starts_at), created_at timestamptz not null default now());
create table public.rest_day_requests (id uuid primary key default gen_random_uuid(), employee_id uuid not null references public.profiles on delete cascade, requested_date date not null, reason text not null check(char_length(reason) between 3 and 500), status request_status not null default 'pending', submitted_at timestamptz not null default now(), reviewed_at timestamptz, reviewed_by uuid references public.profiles, manager_note text, unique(employee_id,requested_date));
create table public.schedules (id uuid primary key default gen_random_uuid(), week_start date not null unique check(extract(isodow from week_start)=1), status schedule_status not null default 'draft', published_at timestamptz, published_by uuid references public.profiles, revision integer not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.shifts (id uuid primary key default gen_random_uuid(), schedule_id uuid not null references public.schedules on delete cascade, employee_id uuid not null references public.profiles on delete cascade, starts_at timestamptz not null, ends_at timestamptz not null check(ends_at>starts_at), label text not null, break_minutes integer not null default 60 check(break_minutes>=0), created_at timestamptz not null default now());
create table public.shift_templates (id uuid primary key default gen_random_uuid(), name text not null unique, starts_at time not null, ends_at time not null, break_minutes integer not null default 60 check(break_minutes>=0));
create table public.scheduling_settings (id boolean primary key default true check(id), week_starts smallint not null default 1 check(week_starts=1), finalization_weekday smallint not null default 5 check(finalization_weekday between 1 and 7), updated_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), recipient_id uuid not null references public.profiles on delete cascade, title text not null, message text not null, read_at timestamptz, created_at timestamptz not null default now());

create index requests_queue_idx on public.rest_day_requests(requested_date,submitted_at) where status='pending';create index shifts_employee_time_idx on public.shifts(employee_id,starts_at,ends_at);create index notifications_recipient_idx on public.notifications(recipient_id,created_at desc);
create or replace function public.is_manager() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.profiles where id=auth.uid() and role='manager' and active)$$;
create or replace function public.my_role() returns account_role language sql stable security definer set search_path=public as $$select role from public.profiles where id=auth.uid()$$;
create or replace function public.my_classification() returns employee_classification language sql stable security definer set search_path=public as $$select classification from public.profiles where id=auth.uid()$$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,full_name,email) values(new.id,coalesce(new.raw_user_meta_data->>'full_name','New employee'),new.email);return new;end$$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;alter table public.class_meetings enable row level security;alter table public.rest_day_requests enable row level security;alter table public.schedules enable row level security;alter table public.shifts enable row level security;alter table public.shift_templates enable row level security;alter table public.scheduling_settings enable row level security;alter table public.notifications enable row level security;
create policy "profiles self read or manager" on public.profiles for select using(id=auth.uid() or public.is_manager());create policy "profiles manager update" on public.profiles for update using(public.is_manager()) with check(public.is_manager());create policy "profiles self contact update" on public.profiles for update using(id=auth.uid()) with check(id=auth.uid() and role=public.my_role() and classification=public.my_classification());
create policy "classes self or manager read" on public.class_meetings for select using(employee_id=auth.uid() or public.is_manager());create policy "classes self write" on public.class_meetings for all using(employee_id=auth.uid()) with check(employee_id=auth.uid());create policy "classes manager write" on public.class_meetings for all using(public.is_manager()) with check(public.is_manager());
create policy "requests self or manager read" on public.rest_day_requests for select using(employee_id=auth.uid() or public.is_manager());create policy "employees submit requests" on public.rest_day_requests for insert with check(employee_id=auth.uid() and status='pending');create policy "employees cancel pending requests" on public.rest_day_requests for update using(employee_id=auth.uid() and status='pending') with check(employee_id=auth.uid() and status='cancelled');create policy "managers review requests" on public.rest_day_requests for update using(public.is_manager()) with check(public.is_manager());
create policy "published schedules visible" on public.schedules for select using(status in('published','revised') or public.is_manager());create policy "managers manage schedules" on public.schedules for all using(public.is_manager()) with check(public.is_manager());create policy "own published shifts" on public.shifts for select using(employee_id=auth.uid() and exists(select 1 from public.schedules s where s.id=schedule_id and s.status in('published','revised')) or public.is_manager());create policy "managers manage shifts" on public.shifts for all using(public.is_manager()) with check(public.is_manager());
create policy "authenticated read templates" on public.shift_templates for select to authenticated using(true);create policy "managers manage templates" on public.shift_templates for all using(public.is_manager()) with check(public.is_manager());create policy "authenticated read settings" on public.scheduling_settings for select to authenticated using(true);create policy "managers manage settings" on public.scheduling_settings for all using(public.is_manager()) with check(public.is_manager());create policy "own notifications" on public.notifications for select using(recipient_id=auth.uid());create policy "own notifications update" on public.notifications for update using(recipient_id=auth.uid()) with check(recipient_id=auth.uid());create policy "managers create notifications" on public.notifications for insert with check(public.is_manager());
